- hosts: localhost
  tasks:
  - name: "Setup the docker Repository"
    yum_repository:
      name: "docker-ce"
      description: "This is my docker software repository"
      baseurl: "https://download.docker.com/linux/centos/7/x86_64/stable/"
      gpgcheck: no


  - name: "Download the Docker Software"
    package:
       name: "docker-ce-18.09.1-3.el7.x86_64"

  - name: "Start the Docker Engine"
    service:
     name: "docker" 
     state: restarted
     enabled: yes

  - name: "Install the Dependencies for the Docker Engine"
    command:
     cmd: "yum install python2 -y"

  - pip:
     name: docker-py


  - name: "Pull image from docker hub"
    docker_image:
            name: "deepakdocker25/cent-ssh:v1"
            source: pull


  - name: "create a docker container"
    docker_container:
       name: "webserver"
       image: "deepakdocker25/cent-ssh:v1"
       state: started
       interactive: yes
       detach: yes
       tty: yes
    register: cont
  - debug:
          var: cont.container.NetworkSettings.IPAddress


- hosts: localhost
  tasks:
  - name: "Updating inventory..."
    blockinfile:
      path: "/root/inventory.txt"
      block: |
        [docker_container]
        {{cont['container']['NetworkSettings']['IPAddress']}} ansible_user=root ansible_ssh_pass=123456 ansible_connection=ssh
      marker: ""


- hosts: docker_container
  tasks:
  - name: "Installing package httpd"
    package:
        name: "httpd"
        state: present

  - name: "Creating webpage"
    copy:
        dest: "/var/www/html/index.html"
        content: "Welcome to my Docker Container!!"

  - name: "Starting services"
    command:
        cmd: /usr/sbin/httpd

